export const {
    DB_HOST = "localhost",
    DB_USER = "root",
    DB_PASSWORD = "",
    DB_DATABASE = "arrive_on_time",
    PORT = 5000,
    NODE_ENV = 'development',
    FRONTEND_URL = "http://localhost:5173",
} = process.env